### ISSUE TITLE
"Pixel's Character Models (pcm) encountered an error during the process_imc event phase"

### ISSUE THREAD

**Issue by PyschoPickles** [PixelDoted/PixelsCharacterModels#1]
My gf and I were looking for a mod so we can add custom animations to our game. We made sure to download everything needed for 1.16.5, but when we loaded in, PCM crashed. All our mods work perfectly together, so maybe there's a mod that PCM doesn't like..?
Here's the crashlog I got. I didn't remove/add anything to the note, so everything here is the exact same as it is in the crashlog.

---- Minecraft Crash Report ----

// My bad. 

Time: 6/22/21 8:22 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$9122/774505085.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$7980/1584295043.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.0.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$481/698977695.call(Unknown Source) [forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
-- MOD pcm --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: com/mrcrayfish/obfuscate/client/model/CustomPlayerModel
		at me.PixelDots.PixelsCharacterModels.Main.processIMC(Main.java:108) ~[?:0.5-1.16.1] {re:classloading}
		at me.PixelDots.PixelsCharacterModels.Main$$Lambda$4427/134393383.accept(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus$$Lambda$2963/158065070.invoke(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus$$Lambda$2561/223939470.invoke(Unknown Source) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.1] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
		at net.minecraftforge.fml.ModContainer$$Lambda$3232/389424956.run(Unknown Source) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Mod File: PCM-0.5-1.16.1(Oct22-2020).jar
	Failure message: Pixel's Character Models (pcm) encountered an error during the process_imc event phase
		java.lang.NoClassDefFoundError: com/mrcrayfish/obfuscate/client/model/CustomPlayerModel
	Mod Version: 0.5
	Mod Issue URL: http://my.issue.tracker/
	Exception message: java.lang.ClassNotFoundException: com.mrcrayfish.obfuscate.client.model.CustomPlayerModel
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.0.9.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at me.PixelDots.PixelsCharacterModels.Main.processIMC(Main.java:108) ~[?:0.5-1.16.1] {re:classloading}
	at me.PixelDots.PixelsCharacterModels.Main$$Lambda$4427/134393383.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2963/158065070.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2561/223939470.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3232/389424956.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 598448280 bytes (570 MB) / 2934439936 bytes (2798 MB) up to 3728736256 bytes (3556 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4000m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8_MOD.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.0
	FML Language Providers: 
		javafml@36.1
		minecraft@1
		kotlinforforge@1.12.2
	Mod List: 
		forge-1.16.5-36.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |COMPLETE  |NOSIGNATURE
		TConstruct-1.16.5-3.0.4.197.jar                   |Tinkers' Construct            |tconstruct                    |3.0.4.197           |COMPLETE  |NOSIGNATURE
		mcw-bridges-1.0.5-mc1.16.5-4.jar                  |Macaw's Bridges               |mcwbridges                    |1.0.5               |COMPLETE  |NOSIGNATURE
		Variant16x-1.16.5-v0.21.4_beta_pre6.jar           |Variant16x                    |variant16x                    |0.21.4_beta_pre6    |COMPLETE  |NOSIGNATURE
		pamhc2trees-1.16.3-1.0.1.jar                      |Pam's HarvestCraft 2 Fruit Tre|pamhc2trees                   |1.0.1               |COMPLETE  |NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.471-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.471   |COMPLETE  |NOSIGNATURE
		pamhc2crops-1.16.3-1.0.2.jar                      |Pam's HarvestCraft 2 Crops    |pamhc2crops                   |version             |COMPLETE  |NOSIGNATURE
		mcw-trapdoors-1.0.2-mc1.16.5.jar                  |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.2               |COMPLETE  |NOSIGNATURE
		mcw-fences-1.0.0-mc1.16.5.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.0               |COMPLETE  |NOSIGNATURE
		jei-1.16.5-7.7.0.106.jar                          |Just Enough Items             |jei                           |7.7.0.106           |COMPLETE  |NOSIGNATURE
		prefab-1.6.5.6.jar                                |Prefab                        |prefab                        |1.6.5.6             |COMPLETE  |NOSIGNATURE
		GeneticAnimals-0_6_29.jar                         |Genetic Animals               |eanimod                       |0_6_29              |COMPLETE  |NOSIGNATURE
		abnormals_core-1.16.5-3.2.0 (1).jar               |Abnormals Core                |abnormals_core                |3.2.0               |COMPLETE  |NOSIGNATURE
		buzzier_bees-1.16.5-3.0.1.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.1               |COMPLETE  |NOSIGNATURE
		astikorcarts-1.16.5-1.1.1.jar                     |AstikorCarts                  |astikorcarts                  |1.1.1               |COMPLETE  |NOSIGNATURE
		pamhc2foodextended-1.16.3-1.0.2.jar               |Pam's HarvestCraft 2 Food Exte|pamhc2foodextended            |version             |COMPLETE  |NOSIGNATURE
		mcw-windows-1.0.3-mc1.16.5.jar                    |Macaw's Windows               |mcwwindows                    |1.0.3               |COMPLETE  |NOSIGNATURE
		upgrade_aquatic-1.16.5-3.1.0 (1).jar              |Upgrade Aquatic               |upgrade_aquatic               |3.1.0               |COMPLETE  |NOSIGNATURE
		Craftable+Saddles+[1.16+All]-1.3.jar              |Craftable Saddles             |craftable_saddles             |1.3                 |COMPLETE  |NOSIGNATURE
		curios-forge-1.16.5-4.0.5.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.2      |COMPLETE  |NOSIGNATURE
		Patchouli-1.16.4-51.jar                           |Patchouli                     |patchouli                     |1.16.4-51           |COMPLETE  |NOSIGNATURE
		Mantle-1.16.5-1.6.109.jar                         |Mantle                        |mantle                        |1.6.109             |COMPLETE  |NOSIGNATURE
		Xaeros_Minimap_21.10.0.3_Forge_1.16.5.jar         |Xaero's Minimap               |xaerominimap                  |21.10.0.3           |COMPLETE  |NOSIGNATURE
		PCM-0.5-1.16.1(Oct22-2020).jar                    |Pixel's Character Models      |pcm                           |0.5                 |ERROR     |NOSIGNATURE
		pamhc2foodcore-1.16.3-1.0.2.jar                   |Pam's HarvestCraft 2 Food Core|pamhc2foodcore                |version             |COMPLETE  |NOSIGNATURE
		gravestone-1.16.5-1.0.4.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.4        |COMPLETE  |NOSIGNATURE
		XaerosWorldMap_1.14.1_Forge_1.16.5.jar            |Xaero's World Map             |xaeroworldmap                 |1.14.1              |COMPLETE  |NOSIGNATURE
		horse_colors-1.16.5-1.6.0.2 (1).jar               |Realistic Horse Genetics      |horse_colors                  |1.16.5-1.6.0.2      |COMPLETE  |NOSIGNATURE
		citadel-1.7.1-1.16.5 (1).jar                      |Citadel                       |citadel                       |1.7.1               |COMPLETE  |NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |COMPLETE  |NOSIGNATURE
		DoubleSlabs-1.16-3.5.0.jar                        |Double Slabs                  |doubleslabs                   |3.5.0               |COMPLETE  |NOSIGNATURE
		obfuscate-0.6.2-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.2               |COMPLETE  |e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		Bookshelf-1.16.5-10.1.12.jar                      |Bookshelf                     |bookshelf                     |10.1.12             |COMPLETE  |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.16.4-2.5.0.271.jar       |Sophisticated Backpacks       |sophisticatedbackpacks        |property(class java.|COMPLETE  |NOSIGNATURE
		mcw-roofs-2.0.1-mc1.16.5-4.jar                    |Macaw's Roofs                 |mcwroofs                      |2.0.1               |COMPLETE  |NOSIGNATURE
		mcw-doors-1.0.3-mc1.16.5.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.3               |COMPLETE  |NOSIGNATURE
		cfm-7.0.0pre22-1.16.3.jar                         |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre22         |COMPLETE  |NOSIGNATURE
		bedspreads-forge-1.16.5-5.1.0.2.jar               |Bedspreads                    |bedspreads                    |1.16.5-5.1.0.2      |COMPLETE  |NOSIGNATURE
		mcw-furniture-2.0.1-mc1.16.5.jar                  |Macaw's Furniture             |mcwfurnitures                 |2.0.1               |COMPLETE  |NOSIGNATURE
		iceandfire-2.1.7-1.16.5 (1).jar                   |Ice and Fire                  |iceandfire                    |2.1.7-1.16.5        |COMPLETE  |NOSIGNATURE
		Hwyla-forge-1.10.11-B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |COMPLETE  |NOSIGNATURE
		Adorn-1.14.1+1.16.5-forge.jar                     |Adorn                         |adorn                         |1.14.1+1.16.5-forge |COMPLETE  |NOSIGNATURE
		JustEnoughResources-1.16.3-0.12.0.100.jar         |Just Enough Resources         |jeresources                   |0.12.0.100          |COMPLETE  |NOSIGNATURE
		horsestandstill-1.16.5-1.0.2.jar                  |Stupid Horse Stand Still      |horsestandstill               |1.16.5-1.0.2        |COMPLETE  |1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0              |COMPLETE  |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		CosmeticArmorReworked-1.16.5-v3a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v3a          |COMPLETE  |5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		chiselsandbits-0.3.4-RELEASE.jar                  |Chisels & bits                |chiselsandbits                |NONE                |COMPLETE  |NOSIGNATURE
		geckolib-forge-1.16.5-3.0.41.jar                  |GeckoLib                      |geckolib3                     |3.0.41              |COMPLETE  |NOSIGNATURE
		ars_nouveau-1.16.5-1.18.7.jar                     |Ars Nouveau                   |ars_nouveau                   |1.18.7              |COMPLETE  |NOSIGNATURE
	Crash Report UUID: 6fef2019-d6ba-4fc5-9147-43290f8a393b
	Patchouli open book context: n/a
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v8.0.01.zip
	OpenGlVersion: 4.5.0 - Build 23.20.16.4973
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount:  4

I apologise for the confusing mod list(We have so many..)  Again, all of our mods work together so I'm thinking there's a mod that PCM doesn't like.

**Comment by PixelDoted** [comment]
Pixel's Character Models - Forge
It seems like PCM-Forge doesn't support Obfuscate 6.2 try using an Older version of obfuscate,
If this doesn't work you'll have to wait till PCM-Forge supports 1.16.5

sorry for the late reply.
