### ISSUE TITLE
Cannot read the array length because "files" is null

### ISSUE THREAD

**Issue by PixelDoted** [PixelDoted/PixelsCharacterModels#9]
Pixel's Character Models - Fabric/Forge
fails to read files from the Presets folder because it doesn't exsist

```
java.lang.NullPointerException: Cannot read the array length because "files" is null
	at me.pixeldots.pixelscharactermodels.gui.PresetsGui.method_25426(PresetsGui.java:94)
	at net.minecraft.class_437.method_25423(class_437.java:387)
	at net.minecraft.class_310.method_1507(class_310.java:986)
	at me.pixeldots.pixelscharactermodels.PCMClient.OpenGUI(PCMClient.java:78)
	at me.pixeldots.pixelscharactermodels.other.KeyBindings.lambda$registerKeyBindings$0(KeyBindings.java:49)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$zcp000$onEndTick(class_310.java:4073)
	at net.minecraft.class_310.method_1574(class_310.java:1808)
	at net.minecraft.class_310.method_1523(class_310.java:1083)
	at net.minecraft.class_310.method_1514(class_310.java:730)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by PixelDoted** [comment]
fixed in ~~V2.0.2~~ V2.0.3  
[Fabric/Quilt](https://modrinth.com/mod/pixels-character-models/version/2.0.3), [Forge](https://modrinth.com/mod/pixels-character-models/version/2.0.3F)
